### PR TITLE
made a search title box

### PR DESCRIPTION
**Pull request by rtdonin**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by ghost** [comment]
That was fast! Let’s see...

**Review by ghost — CHANGES_REQUESTED** [review]
Some issues need to be fixed before you can merge your PR:
 - I have no idea why, but I've been told that we are not allowed to update ".github/workflows/wilco-actions.yml". Please make sure to revert your changes before merging your PR.

**Comment by rtdonin** [comment]
Trying this again

**Comment by rtdonin** [comment]
try this again. reverted file. I hope.

**Review by ghost — APPROVED** [review]
Yay, it works! Go ahead and merge the PR.

**Pull request merged**
